from __future__ import annotations

import argparse
from datetime import date, time
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from vitalle_ops.support import load_local_env  # noqa: E402
from vitalle_ops.store import (  # noqa: E402
    sync_daily_operation,
    upsert_organization,
    upsert_sector,
    upsert_system_setting,
    upsert_task_template,
    upsert_unit,
    upsert_user,
    upsert_user_profile,
    upsert_user_sector_assignment,
)


ORGANIZATION_ID = "vitalle-odontologia"
UNIT_ID = "vitalle-main"

SECTORS = [
    {
        "id": "sector-avaliador",
        "name": "AVALIADOR",
        "slug": "avaliador",
        "description": "Responsável pela supervisão operacional e clínica, conferência de procedimentos, registros, pagamentos, tratativas pendentes e reagendamentos.",
        "color": "#0f766e",
        "icon": "clipboard-check",
        "sort_order": 1,
    },
    {
        "id": "sector-asb",
        "name": "AUXILIAR EM SAÚDE BUCAL — ASB",
        "slug": "asb",
        "description": "Responsável pelo suporte clínico, preparo e manutenção dos consultórios, processamento de artigos odontológicos na CME, biossegurança e encerramento operacional.",
        "color": "#2563eb",
        "icon": "syringe",
        "sort_order": 2,
    },
    {
        "id": "sector-secretaria",
        "name": "SECRETARIA / RECEPÇÃO",
        "slug": "secretaria-recepcao",
        "description": "Responsável pelo primeiro atendimento, organização da agenda, confirmação e reagendamento de consultas, apoio financeiro-operacional, cobrança e fechamento das rotinas administrativas.",
        "color": "#7c3aed",
        "icon": "calendar-clock",
        "sort_order": 3,
    },
    {
        "id": "sector-marketing",
        "name": "MARKETING E COMERCIAL",
        "slug": "marketing-comercial",
        "description": "Responsável pelas rotinas de marketing, relacionamento comercial, produção de conteúdos, campanhas, eventos, resgate de clientes e experiência pós-venda.",
        "color": "#ca8a04",
        "icon": "megaphone",
        "sort_order": 4,
    },
]

USERS = [
    {
        "id": "demo-admin",
        "email": "admin@vitalle.local",
        "full_name": "Admin Vitalle",
        "display_name": "Admin Vitalle",
        "role": "admin",
        "title": "Administrador",
        "sector_ids": [sector["id"] for sector in SECTORS],
    },
    {
        "id": "demo-gestor",
        "email": "gestor@vitalle.local",
        "full_name": "Gestor Vitalle",
        "display_name": "Gestor Vitalle",
        "role": "manager",
        "title": "Gestor Operacional",
        "sector_ids": [sector["id"] for sector in SECTORS],
    },
    {
        "id": "demo-avaliador",
        "email": "avaliador@vitalle.local",
        "full_name": "Mariana Silva",
        "display_name": "Mariana Silva",
        "role": "collaborator",
        "title": "Avaliador",
        "sector_ids": ["sector-avaliador"],
    },
    {
        "id": "demo-asb",
        "email": "asb@vitalle.local",
        "full_name": "Ana Costa",
        "display_name": "Ana Costa",
        "role": "collaborator",
        "title": "ASB",
        "sector_ids": ["sector-asb"],
    },
    {
        "id": "demo-secretaria",
        "email": "secretaria@vitalle.local",
        "full_name": "Maria Ferreira",
        "display_name": "Maria Ferreira",
        "role": "collaborator",
        "title": "Secretaria",
        "sector_ids": ["sector-secretaria"],
    },
    {
        "id": "demo-marketing",
        "email": "marketing@vitalle.local",
        "full_name": "Paula Lima",
        "display_name": "Paula Lima",
        "role": "collaborator",
        "title": "Marketing e Comercial",
        "sector_ids": ["sector-marketing"],
    },
]


def template(
    template_id: str,
    *,
    sector_id: str,
    title: str,
    description: str = "",
    task_type: str = "STANDARD",
    start: str,
    due: str,
    priority: str = "NORMAL",
    critical: bool = False,
    recurrence_type: str = "WEEKDAYS",
    weekdays: list[int] | None = None,
    month_days: list[int] | None = None,
    weeks_of_month: list[int] | None = None,
    goal_target: int | None = None,
    goal_unit: str = "",
    goal_group_key: str = "",
    requires_comment: bool = False,
    requires_evidence: bool = False,
    requires_review: bool = False,
    allow_not_applicable: bool = True,
    conditional: bool = False,
    instructions: str = "",
    subtasks: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    return {
        "id": template_id,
        "organization_id": ORGANIZATION_ID,
        "unit_id": UNIT_ID,
        "sector_id": sector_id,
        "title": title,
        "description": description,
        "task_type": task_type,
        "start_time": time.fromisoformat(start),
        "due_time": time.fromisoformat(due),
        "priority": priority,
        "is_critical": critical,
        "goal_target": goal_target,
        "goal_unit": goal_unit,
        "goal_group_key": goal_group_key,
        "requires_comment_on_completion": requires_comment,
        "requires_evidence": requires_evidence,
        "requires_manager_review": requires_review,
        "allow_not_applicable": allow_not_applicable,
        "is_conditional": conditional,
        "instructions": instructions,
        "active": True,
        "recurrence_rule": {
            "recurrence_type": recurrence_type,
            "interval_value": 1,
            "weekdays": weekdays or [],
            "month_days": month_days or [],
            "weeks_of_month": weeks_of_month or [],
            "custom_rule_json": {},
            "start_date": date(2026, 7, 1),
            "end_date": None,
        },
        "subtasks": subtasks or [],
    }


TEMPLATES = [
    template(
        "avaliador-conferencia-procedimentos",
        sector_id="sector-avaliador",
        title="CONFERÊNCIA DOS PROCEDIMENTOS DO DIA ANTERIOR",
        description="Conferir todos os procedimentos realizados no dia anterior, incluindo baixa no sistema e conferência da ficha física.",
        task_type="REVIEW",
        start="09:00:00",
        due="09:30:00",
        priority="HIGH",
        critical=False,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Conferir procedimentos realizados no dia anterior.", "sort_order": 1},
            {"title": "Conferir baixa dos procedimentos no sistema.", "sort_order": 2},
            {"title": "Conferir ficha física.", "sort_order": 3},
            {"title": "Verificar pagamentos em N.A.", "sort_order": 4},
            {"title": "Verificar eventuais pendências financeiras.", "sort_order": 5},
        ],
    ),
    template(
        "avaliador-pasta-vermelha",
        sector_id="sector-avaliador",
        title="PASTA VERMELHA — TRATATIVAS",
        description="Conversar com pacientes ou responsáveis por procedimentos pendentes.",
        task_type="GOAL",
        start="11:00:00",
        due="12:00:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        goal_target=5,
        goal_unit="tratativas",
        goal_group_key="avaliador-pasta-vermelha",
        instructions="Registrar cada retorno no controle operacional.",
    ),
    template(
        "avaliador-almoco-invertido",
        sector_id="sector-avaliador",
        title="ALMOÇO INVERTIDO",
        description="Almoço invertido com o clínico geral.",
        task_type="STANDARD",
        start="12:00:00",
        due="13:30:00",
        priority="LOW",
        recurrence_type="WEEKDAYS",
        allow_not_applicable=True,
    ),
    template(
        "avaliador-retomar-pasta-vermelha",
        sector_id="sector-avaliador",
        title="RETOMAR PASTA VERMELHA",
        description="Retomar tratativas pendentes e confirmar cumprimento da meta mínima diária.",
        task_type="GOAL",
        start="15:00:00",
        due="17:00:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        goal_target=5,
        goal_unit="tratativas",
        goal_group_key="avaliador-pasta-vermelha",
        instructions="Utiliza a mesma meta diária das tratativas das 11:00.",
    ),
    template(
        "avaliador-caixas-perguntas",
        sector_id="sector-avaliador",
        title="CAIXAS DE PERGUNTAS E CONTEÚDO",
        description="Responder caixas de perguntas e gravar conteúdo.",
        task_type="STANDARD",
        start="17:00:00",
        due="17:45:00",
        priority="NORMAL",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "avaliador-reagendamentos",
        sector_id="sector-avaliador",
        title="CONFERÊNCIA DE REAGENDAMENTOS",
        description="Verificar pacientes atendidos que necessitam de reagendamento e confirmar registro no sistema ou controle interno.",
        task_type="REVIEW",
        start="18:00:00",
        due="18:30:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Verificar pacientes atendidos que necessitam de reagendamento.", "sort_order": 1},
            {"title": "Verificar pacientes faltantes.", "sort_order": 2},
            {"title": "Confirmar se todos foram reagendados.", "sort_order": 3},
            {"title": "Confirmar registro no sistema ou controle interno.", "sort_order": 4},
        ],
    ),
    template(
        "avaliador-encerramento-unidade",
        sector_id="sector-avaliador",
        title="ENCERRAMENTO DA UNIDADE",
        description="Executar apenas quando necessário.",
        task_type="CONDITIONAL",
        start="19:00:00",
        due="19:30:00",
        priority="HIGH",
        recurrence_type="WEEKDAYS",
        conditional=True,
        allow_not_applicable=True,
        subtasks=[
            {"title": "Desligar todos os equipamentos necessários.", "sort_order": 1},
            {"title": "Desligar luzes da clínica.", "sort_order": 2},
            {"title": "Trancar a clínica.", "sort_order": 3},
            {"title": "Assegurar o encerramento operacional da unidade.", "sort_order": 4},
        ],
        instructions="Permitir registrar 'NÃO NECESSÁRIO HOJE'.",
    ),
    template(
        "avaliador-palestra-mensal",
        sector_id="sector-avaliador",
        title="PALESTRA EM EMPRESAS OU ESCOLAS",
        description="Rotina mensal de palestra.",
        task_type="GOAL",
        start="09:00:00",
        due="18:00:00",
        priority="NORMAL",
        critical=False,
        recurrence_type="MONTHLY",
        month_days=[1],
        goal_target=1,
        goal_unit="palestra",
        goal_group_key="avaliador-palestra-mensal",
    ),
    template(
        "asb-abertura-consultorios",
        sector_id="sector-asb",
        title="ABERTURA OPERACIONAL DOS CONSULTÓRIOS",
        description="Ligar compressor, bomba de vácuo, cadeiras odontológicas e TVs; realizar relatório geral das salas.",
        task_type="OPENING",
        start="09:00:00",
        due="09:30:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Ligar compressor.", "sort_order": 1},
            {"title": "Ligar bomba de vácuo.", "sort_order": 2},
            {"title": "Ligar cadeiras odontológicas.", "sort_order": 3},
            {"title": "Ligar televisores dos consultórios.", "sort_order": 4},
            {"title": "Realizar relatório geral das salas.", "sort_order": 5},
            {"title": "Verificar materiais.", "sort_order": 6},
            {"title": "Verificar descartáveis.", "sort_order": 7},
            {"title": "Verificar insumos.", "sort_order": 8},
        ],
    ),
    template(
        "asb-processamento-manha",
        sector_id="sector-asb",
        title="PROCESSAMENTO E ESTERILIZAÇÃO",
        description="Limpeza, secagem, embalagem, esterilização e teste de autoclave.",
        task_type="CHECKLIST",
        start="10:00:00",
        due="11:30:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Limpeza dos materiais.", "sort_order": 1},
            {"title": "Secagem.", "sort_order": 2},
            {"title": "Embalagem.", "sort_order": 3},
            {"title": "Esterilização.", "sort_order": 4},
            {"title": "Emissão ou preenchimento dos relatórios.", "sort_order": 5},
            {"title": "Realizar teste de autoclave.", "sort_order": 6},
        ],
    ),
    template(
        "asb-almoco",
        sector_id="sector-asb",
        title="ALMOÇO",
        description="Intervalo operacional.",
        task_type="STANDARD",
        start="12:00:00",
        due="13:30:00",
        priority="LOW",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "asb-processamento-tarde",
        sector_id="sector-asb",
        title="SEGUNDO CICLO DE PROCESSAMENTO E ESTERILIZAÇÃO",
        description="Segundo ciclo do processo ao longo da tarde.",
        task_type="CHECKLIST",
        start="15:00:00",
        due="16:15:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Limpeza dos materiais.", "sort_order": 1},
            {"title": "Secagem.", "sort_order": 2},
            {"title": "Embalagem.", "sort_order": 3},
            {"title": "Esterilização.", "sort_order": 4},
            {"title": "Emissão ou preenchimento dos relatórios.", "sort_order": 5},
        ],
    ),
    template(
        "asb-intervalo",
        sector_id="sector-asb",
        title="INTERVALO",
        description="Intervalo operacional curto.",
        task_type="STANDARD",
        start="16:30:00",
        due="16:45:00",
        priority="LOW",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "asb-fechamento-consultorios",
        sector_id="sector-asb",
        title="FECHAMENTO CLÍNICO E DOS CONSULTÓRIOS",
        description="Rotina de fechamento da clínica e consultórios.",
        task_type="CLOSING",
        start="18:00:00",
        due="18:45:00",
        priority="CRITICAL",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Retirar todos os lixos dos consultórios.", "sort_order": 1},
            {"title": "Substituir os sacos de lixo.", "sort_order": 2},
            {"title": "Limpar consultórios.", "sort_order": 3},
            {"title": "Retirar materiais contaminados.", "sort_order": 4},
            {"title": "Desligar TVs.", "sort_order": 5},
            {"title": "Desligar ar-condicionado.", "sort_order": 6},
            {"title": "Desligar luzes dos consultórios.", "sort_order": 7},
            {"title": "Desligar cadeiras odontológicas.", "sort_order": 8},
            {"title": "Desligar compressor.", "sort_order": 9},
            {"title": "Realizar esgotamento do reservatório do compressor.", "sort_order": 10},
            {"title": "Desligar bomba de vácuo.", "sort_order": 11},
            {"title": "Desligar equipamento de RX.", "sort_order": 12},
            {"title": "Desligar computador do RX.", "sort_order": 13},
        ],
    ),
    template(
        "asb-sexta-conferencia",
        sector_id="sector-asb",
        title="CONFERÊNCIA SEMANAL",
        description="Conferência semanal de instrumentais, medicamentos e reposições.",
        task_type="CHECKLIST",
        start="09:00:00",
        due="10:00:00",
        priority="HIGH",
        critical=False,
        recurrence_type="SPECIFIC_WEEKDAYS",
        weekdays=[5],
        subtasks=[
            {"title": "Conferir vencimentos dos instrumentais esterilizados.", "sort_order": 1},
            {"title": "Conferir medicamentos em estoque.", "sort_order": 2},
            {"title": "Identificar materiais vencidos.", "sort_order": 3},
            {"title": "Realizar descarte conforme processo interno quando aplicável.", "sort_order": 4},
            {"title": "Realizar reembalagem ou reesterilização quando aplicável.", "sort_order": 5},
            {"title": "Atualizar lista de compras.", "sort_order": 6},
            {"title": "Atualizar lista de reposições.", "sort_order": 7},
        ],
    ),
    template(
        "secretaria-abertura",
        sector_id="sector-secretaria",
        title="ABERTURA DA RECEPÇÃO E CONFERÊNCIA DA AGENDA",
        description="Ligar computadores, TVs e celular institucional; conferir agendamentos e confirmação de pacientes.",
        task_type="OPENING",
        start="09:00:00",
        due="09:30:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Ligar computadores da recepção.", "sort_order": 1},
            {"title": "Ligar TVs.", "sort_order": 2},
            {"title": "Ligar celular institucional.", "sort_order": 3},
            {"title": "Conferir agendamentos do dia.", "sort_order": 4},
            {"title": "Separar pacientes confirmados.", "sort_order": 5},
            {"title": "Identificar pacientes não confirmados.", "sort_order": 6},
            {"title": "Retornar imediatamente aos pacientes não confirmados.", "sort_order": 7},
        ],
    ),
    template(
        "secretaria-financeiro",
        sector_id="sector-secretaria",
        title="CONFERÊNCIA FINANCEIRA E ADMINISTRATIVA",
        description="Baixar boletos, conferir Pix e registrar pagamentos.",
        task_type="CHECKLIST",
        start="10:00:00",
        due="11:30:00",
        priority="HIGH",
        critical=False,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Baixar boletos.", "sort_order": 1},
            {"title": "Conferir Pix.", "sort_order": 2},
            {"title": "Registrar pagamentos no sistema.", "sort_order": 3},
            {"title": "Verificar e-mail institucional.", "sort_order": 4},
            {"title": "Verificar contas recebidas.", "sort_order": 5},
            {"title": "Verificar notas fiscais.", "sort_order": 6},
            {"title": "Verificar pedidos.", "sort_order": 7},
            {"title": "Verificar documentos importantes.", "sort_order": 8},
            {"title": "Imprimir documentos necessários.", "sort_order": 9},
            {"title": "Encaminhar contas a pagar ao responsável financeiro.", "sort_order": 10},
        ],
    ),
    template(
        "secretaria-almoco",
        sector_id="sector-secretaria",
        title="ALMOÇO",
        description="Intervalo operacional.",
        task_type="STANDARD",
        start="12:00:00",
        due="13:30:00",
        priority="LOW",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "secretaria-cobranca-inadimplentes",
        sector_id="sector-secretaria",
        title="COBRANÇA DE INADIMPLENTES",
        description="Iniciar cobrança de inadimplentes.",
        task_type="GOAL",
        start="14:00:00",
        due="16:00:00",
        priority="HIGH",
        critical=True,
        recurrence_type="WEEKDAYS",
        goal_target=10,
        goal_unit="negociações",
        goal_group_key="secretaria-cobranca",
        instructions="Priorizar débitos mais recentes. Registrar contatos realizados.",
    ),
    template(
        "secretaria-intervalo",
        sector_id="sector-secretaria",
        title="INTERVALO",
        description="Intervalo curto.",
        task_type="STANDARD",
        start="16:00:00",
        due="16:15:00",
        priority="LOW",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "secretaria-fechamento",
        sector_id="sector-secretaria",
        title="FECHAMENTO ADMINISTRATIVO",
        description="Fechamento de caixa, diárias e fichas clínicas.",
        task_type="CLOSING",
        start="18:00:00",
        due="18:45:00",
        priority="CRITICAL",
        critical=True,
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Realizar fechamento de caixa.", "sort_order": 1},
            {"title": "Realizar pagamento das diárias dos especialistas ou dentistas parceiros.", "sort_order": 2},
            {"title": "Reunir as fichas clínicas dos atendimentos do dia.", "sort_order": 3},
            {"title": "Colocar as fichas na mesa do Avaliador para conferência.", "sort_order": 4},
        ],
    ),
    template(
        "secretaria-relatorio-diario",
        sector_id="sector-secretaria",
        title="RELATÓRIO DIÁRIO",
        description="Revisar e finalizar o relatório operacional diário.",
        task_type="REVIEW",
        start="18:30:00",
        due="19:00:00",
        priority="HIGH",
        critical=False,
        recurrence_type="WEEKDAYS",
    ),
    template(
        "marketing-conteudo",
        sector_id="sector-marketing",
        title="REDES SOCIAIS E CONTEÚDO",
        description="Executar as atividades de conteúdo previstas para o dia.",
        task_type="CHECKLIST",
        start="09:00:00",
        due="10:00:00",
        priority="HIGH",
        recurrence_type="WEEKDAYS",
        subtasks=[
            {"title": "Realizar postagens nas redes sociais.", "sort_order": 1},
            {"title": "Editar vídeos para divulgação.", "sort_order": 2},
            {"title": "Editar conteúdos de campanhas.", "sort_order": 3},
            {"title": "Executar rotinas semanais de conteúdo conforme planejamento.", "sort_order": 4},
        ],
    ),
    template(
        "marketing-planejamento-posts",
        sector_id="sector-marketing",
        title="PLANEJAMENTO DE POSTS",
        description="Gerar cinco posts para a semana, com programação de uma postagem por dia.",
        task_type="GOAL",
        start="09:00:00",
        due="10:30:00",
        priority="HIGH",
        recurrence_type="SPECIFIC_WEEKDAYS",
        weekdays=[1],
        goal_target=5,
        goal_unit="posts preparados",
        goal_group_key="marketing-posts",
    ),
    template(
        "marketing-caixa-perguntas",
        sector_id="sector-marketing",
        title="CAIXA DE PERGUNTAS",
        description="Caixas de perguntas e reels em dias alternados.",
        task_type="GOAL",
        start="09:00:00",
        due="10:00:00",
        priority="HIGH",
        recurrence_type="SPECIFIC_WEEKDAYS",
        weekdays=[1, 3, 5],
        goal_target=5,
        goal_unit="perguntas",
        goal_group_key="marketing-caixa-perguntas",
    ),
    template(
        "marketing-reels",
        sector_id="sector-marketing",
        title="REELS",
        description="Produzir reels para o calendário da semana.",
        task_type="GOAL",
        start="09:00:00",
        due="10:00:00",
        priority="HIGH",
        recurrence_type="SPECIFIC_WEEKDAYS",
        weekdays=[1, 3, 5],
        goal_target=2,
        goal_unit="reels",
        goal_group_key="marketing-reels",
    ),
    template(
        "marketing-planejamento-mensal",
        sector_id="sector-marketing",
        title="PLANEJAMENTO MENSAL",
        description="Planejar campanhas, panfletos, palestras, mimos, chamadas e postagens do próximo mês.",
        task_type="CHECKLIST",
        start="09:00:00",
        due="10:30:00",
        priority="HIGH",
        recurrence_type="MONTHLY",
        month_days=[1],
        subtasks=[
            {"title": "Planejar campanhas do mês seguinte.", "sort_order": 1},
            {"title": "Planejar panfletos.", "sort_order": 2},
            {"title": "Planejar palestras.", "sort_order": 3},
            {"title": "Planejar mimos.", "sort_order": 4},
            {"title": "Planejar chamadas.", "sort_order": 5},
            {"title": "Planejar postagens.", "sort_order": 6},
        ],
    ),
    template(
        "marketing-eventos",
        sector_id="sector-marketing",
        title="EVENTOS COMERCIAIS E INSTITUCIONAIS",
        description="Organizar palestras, ações em escolas, ações em empresas e demandas comerciais.",
        task_type="STANDARD",
        start="10:00:00",
        due="11:30:00",
        priority="NORMAL",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "marketing-almoco",
        sector_id="sector-marketing",
        title="ALMOÇO",
        description="Intervalo operacional.",
        task_type="STANDARD",
        start="13:30:00",
        due="15:00:00",
        priority="LOW",
        recurrence_type="WEEKDAYS",
    ),
    template(
        "marketing-resgate-clientes",
        sector_id="sector-marketing",
        title="RESGATE DE CLIENTES",
        description="Realizar resgate de clientes antigos e novos.",
        task_type="GOAL",
        start="15:00:00",
        due="16:30:00",
        priority="HIGH",
        recurrence_type="WEEKDAYS",
        goal_target=None,
        goal_unit="contatos",
        goal_group_key="marketing-resgate-clientes",
        instructions="Meta opcional definida pelo administrador.",
    ),
    template(
        "marketing-pos-venda",
        sector_id="sector-marketing",
        title="EXPERIÊNCIA DO CLIENTE E PÓS-VENDA",
        description="Entrar em contato com clientes atendidos e acompanhar a experiência pós-venda.",
        task_type="STANDARD",
        start="17:00:00",
        due="18:00:00",
        priority="NORMAL",
        recurrence_type="WEEKDAYS",
    ),
]


def seed_core() -> None:
    upsert_organization(
        {
            "id": ORGANIZATION_ID,
            "name": "Vitalle Odontologia & Harmonização",
            "slug": "vitalle-odontologia",
            "timezone": "America/Sao_Paulo",
            "is_active": True,
        }
    )
    upsert_unit(
        {
            "id": UNIT_ID,
            "organization_id": ORGANIZATION_ID,
            "name": "Vitalle Principal",
            "slug": "vitalle-main",
            "timezone": "America/Sao_Paulo",
            "is_active": True,
            "sort_order": 1,
        }
    )
    upsert_system_setting(
        {
            "organization_id": ORGANIZATION_ID,
            "unit_id": UNIT_ID,
            "key": "timezone",
            "value_json": {"value": "America/Sao_Paulo"},
            "updated_by": None,
        }
    )
    for sector in SECTORS:
        upsert_sector(
            {
                **sector,
                "organization_id": ORGANIZATION_ID,
                "unit_id": UNIT_ID,
                "status": "active",
            }
        )
    for payload in TEMPLATES:
        upsert_task_template(payload)


def seed_demo_users() -> None:
    for user in USERS:
        upsert_user(
            {
                "id": user["id"],
                "organization_id": ORGANIZATION_ID,
                "unit_id": UNIT_ID,
                "email": user["email"],
                "full_name": user["full_name"],
                "role": user["role"],
                "is_active": True,
                "is_demo": True,
            }
        )
        upsert_user_profile(
            {
                "user_id": user["id"],
                "display_name": user["display_name"],
                "title": user["title"],
                "bio": "",
            }
        )
        for index, sector_id in enumerate(user["sector_ids"]):
            upsert_user_sector_assignment(
                {
                    "user_id": user["id"],
                    "sector_id": sector_id,
                    "is_primary": index == 0,
                    "is_active": True,
                }
            )


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed Vitalle OPS demo data")
    parser.add_argument("--demo-users", action="store_true", help="Seed demo auth/profile personas too")
    parser.add_argument("--sync-today", action="store_true", help="Generate today's daily operation after seeding")
    args = parser.parse_args()
    load_local_env()

    seed_core()
    if args.demo_users:
        seed_demo_users()
    if args.sync_today:
        sync_daily_operation(ORGANIZATION_ID, UNIT_ID, date.today(), "America/Sao_Paulo", "seed", actor_user_id="demo-admin")

    print(
        {
            "organization_id": ORGANIZATION_ID,
            "unit_id": UNIT_ID,
            "sectors": len(SECTORS),
            "templates": len(TEMPLATES),
            "demo_users": bool(args.demo_users),
            "synced_today": bool(args.sync_today),
        }
    )


if __name__ == "__main__":
    main()
